### ISSUE TITLE
Switch to LLD linker on Windows by default

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-ecosystem#15]
For our project we find using LLD instead 2x faster for full builds, and 5x faster for incremental builds, compared to the default MSVC linker. This is huge and essential for us, so we enable it manually in `.cargo/config`:

```
[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"
```

It would be nice if this was the default instead on Windows, esp. if it also made it possible to not have to install the Visual Studio Build Tools?

When using LLD Windows we do get this warning, but haven't been an issue for us:
```
warning: not embedding natvis: lld-link may not support the flag
```

Related umbrella issue in rust-gamedev WG: https://github.com/rust-gamedev/wg/issues/50

Tracking issue:
- [ ] [`rust`: Linking with LLD #39915](https://github.com/rust-lang/rust/issues/39915)
- [ ] [`rust`: Use lld by default on x64 msvc windows #71520](https://github.com/rust-lang/rust/issues/71520)

**Comment by repi** [comment]
We've been happily ussing LLD as our only linker on Windows now for over a year without any real problems, and still would like to see it become supported in Rust without having to have full LLVM manually installed. And ideally, eventually, be the default linker on Windows.

Found another tracking issue about this specifically in Rust https://github.com/rust-lang/rust/issues/71520

**Comment by repi** [comment]
As this is easy enough to enable in our own workspaces and there is a Rust tracking issue for it, closing this issue on our end.

**Comment by frederikhors** [comment]
I'm on Windows 10 x64 with:
`rustup 1.25.1 (bb60b1e89 2022-07-12)`
`rustc 1.66.1 (90743e729 2023-01-10)` 
`MSVC v143` installed with Visual Studio Installer from Microsoft.

If I open a Rust project and change a simple char in code (eg: a variable value from 1 to 2) it re-builds the project (using watchexec) in 12 seconds.

I installed `llvm` and used this in global cargo config file (`C:/Users/<username>/.cargo/config`)

```
[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"
```

After a `cargo clean` and an initial re-build (debug mode, 2 minutes, the same as without `lld`) the time is the same (maybe even worse than 1 second).

Can you confirm?

**Comment by frederikhors** [comment]
I'm on Windows 10 x64 with:
`rustup 1.25.1 (bb60b1e89 2022-07-12)`
`rustc 1.66.1 (90743e729 2023-01-10)` 
`MSVC v143` installed with Visual Studio Installer from Microsoft.

If I open a Rust project and change a simple char in code (eg: a variable value from 1 to 2) it re-builds the project (using watchexec) in 12 seconds.

I installed `llvm` and used this in global cargo config file (`C:/Users/<username>/.cargo/config`)

```
[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"
```

After a `cargo clean` and an initial re-build (debug mode, 2 minutes, the same as without `lld`) the time is the same (maybe even worse than 1 second).

So no change with or without LLD.

**Can you confirm or am I wrong?**

How to get faster incremental (development) builds?

**Comment by frederikhors** [comment]
@repi can you confirm that using lld-link.exe today make compilation still faster? I'm using MSVC latest as of today.
