### ISSUE TITLE
High-performance low-level cross-platform audio library

### ISSUE THREAD

**Issue by hrydgard** [EmbarkStudios/rust-ecosystem#24]
The Rust ecosystem does not seem to have a fully-featured low-level audio library. Basically, we want a fast way to stream raw audio to and from the audio device, plus auxiliary features like selecting the audio device and so on. Clean shutdown and restart during a run is important.

Current alternatives:

## cpal (currently using)
https://github.com/tomaka/cpal
  * "Best" alternative found and current choice. The only natively Rust one that doesn't try to compile a C++ library dependency
  * Has its own event loop, requiring a dedicated audio thread and undesirable synchronization machinery even on platforms where that's not required. Also takes over a thread "forever" and can't be shut down (https://github.com/tomaka/cpal/issues/245).

## rust-portaudio
https://github.com/RustAudio/rust-portaudio
  * C binding that doesn't currently build on Windows
  * Runs its own event loop
  * The original C library is very popular and probably very compatible, so that's a plus maybe
  * License issues?

## soundio-rs
https://github.com/Timmmm/soundio-rs
  * C binding that doesn't currently build on Windows
  * Runs its own event loop
  * Potential license issues

**Comment by icefoxen** [comment]
I'm interested in contributing to cpal, is there anything I could do to make the design better?

**Comment by hrydgard** [comment]
Agreed, that looks like a big step forward.
