### ISSUE TITLE
Broken Travis Badges on crates.io

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/rust-ecosystem#32]
There is a [bug](https://github.com/rust-lang/crates.io/issues/1392) on crates.io for Travis badges being broken due to the change of Travis from .org to .com, all of our repos are on travis-ci.com, and thus are currently affected by this bug.

**Comment by repi** [comment]
We're moving away from Travis (to GitHub Actions) so this will be less relevant for us. Closing
