### ISSUE TITLE
Migrate away from winapi 0.2

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-ecosystem#42]
Thanks to the new Cargo nightly [`-Z timings`](https://internals.rust-lang.org/t/exploring-crate-graph-build-times-with-cargo-build-ztimings/10975/5) I saw that our 3.5 min Windows release build was spending 65 seconds building just the old `winapi 0.2` crate.

The wall time itself, while very high, is not a major problem as this was a larger from scratch build and lots of cores available, but what the timings clearly showed was that it pushed out a lot of build steps because there were tons of small and big crates that had dependencies on `winapi 0.2` directly or indirectly and as such couldn't even start until that had been built.

So want to fully get rid of `winapi 0.2` crate in our builds and migrate the crates that we are using to the faster and better `winapi 0.3` or, in some cases, remove them.

Current crates that use (directly or indirectly) that uses `winapi 0.2`:

- [x] `iovec:`: This is the most important as huge ecosystem depend on this small crate. [PR fix filed](https://github.com/carllerche/iovec/pull/25) 
- [x] `app_dirs:` Abandoned crate, switched to [`app_dirs2`](https://github.com/app-dirs-rs/app_dirs2) instead and [PR fix](https://github.com/app-dirs-rs/app_dirs2/pull/2) was merged & published in 7 minutes (!)
- [x] `mio`: In-progress v0.7 is using latest winapi, v0.6 will stay on `winapi 0.2`. May just have to wait for v0.7?
- [x] `notify`: Unmaintained crate, leaf dependency so less important but should find alternative or get it updated. Related PR: https://github.com/notify-rs/notify/pull/217
- [x] `wasmer-runtime-core`: From [page_size](https://github.com/Elzair/page_size_rs). Is there a more modern/maintained equivalent that they can switch to?
- [x] `tokio` Update to mio 0.7 https://github.com/tokio-rs/tokio/issues/1190
- [x] Ecosystem upgrade to new `tokio` 0.3
- [x] `winit` uses mio 0.6

Once we have those resolved:, we want to allow be able to disallow `winapi 0.2` in our projects:
- [x] `cargo-deny`: https://github.com/EmbarkStudios/cargo-deny/issues/28

**Comment by memoryruins** [comment]
Noticed similar results trying out `-Ztimings` on rust-analyzer while on windows http://gistpreview.github.io/?4a6eafbb1f4786c534143c959876f38f cc @matklad 

For `notify`, it directly uses `winapi 0.3`; however, its dep `kernel32-sys` pulls in `winapi 0.2`. I mentioned this to @rep-nop, and they saw that the calls to `kernel32-sys` could be easily replaced. I believe they are working on a PR now.

p.s. notify is currently looking for new maintainers https://github.com/notify-rs/notify/issues/209

**Comment by repi** [comment]
@memoryruins Awesome thanks! `notify` is a good library, hope it finds a new good home

**Comment by rep-nop** [comment]
`notify` PR has been merged :)

**Comment by crlf0710** [comment]
Maybe it's possible to do the semver tricks and make 0.2 crates reexports of 0.3 one

**Comment by hrydgard** [comment]
@repi looks like the iovec fix was merged

**Comment by hrydgard** [comment]
Fixing wasmer: https://github.com/wasmerio/wasmer/pull/948

**Comment by hrydgard** [comment]
The page_size maintainer finally woke up and merged my pull request, so as soon as wasmer upgrades to a new page_size, we'll be down to a single remaining dependency on winapi 0.2! (mio)

**Comment by repi** [comment]
Nice, and `mio` 0.7-alpha.1 that was released a few days ago has upgraded to `winapi` 0.3 also. Though likely will take a while for the rest of the stack to use it.

https://tokio.rs/blog/2019-12-mio-v0.7-alpha.1/

**Comment by repi** [comment]
`mio` 0.7 has now been released! Just waiting for `tokio` to update and use it now and then this can finally be closed and we won't need `winapi` 0.2 anymore!

**Comment by repi** [comment]
Still waiting for `tokio` to actually upgrade to `mio` 0.7.

Also noticed that the old winapi 0.2 doesn't support building for `aarch64-pc-windows-msvc` (Windows on Arm), so this is a blocker for that.

**Comment by Jake-Shadle** [comment]
Not that I don't mind getting rid of 0.2, but is Windows Arm actually a relevant target?

**Comment by repi** [comment]
@Jake-Shadle in general no 😀 but something I'm personally just curious about experimenting with

**Comment by hrydgard** [comment]
Windows Arm might become important in the coming years. Or not. Time will tell. 

It's unclear what's holding Tokio up from upgrading though...

**Comment by repi** [comment]
New `tokio` 0.3 released today that finally does upgrade `mio` to 0.7 🎉 https://github.com/tokio-rs/tokio/blob/master/tokio/CHANGELOG.md#030-october-15-2020

now just need `hyper`, `h2`, `reqwest`, `tonic`, `tower` to be upgraded to use and we are good to go :)

**Comment by repi** [comment]
Now finally with the major `tokio` upgrades to 1.0 and `mio` they no longer bring in winapi 0.2. Unfortunately found 2 more ecosystem dependencies that still bring in old winapi 0.2: `winit` (event latest 0.24) and `notify` 0.4 (unmaintained). Soo close, but not solved yet.

**Comment by bnjbvr** [comment]
`notify` and `winit` now use both `mio` 0.7+, and while we're not using the latest `winit` in our project yet, the dependency on `winapi 0.2` has been removed away from all these crates, so I think we can finally close this! 🥳
