### ISSUE TITLE
Update open-sourcing.md

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/rust-ecosystem#46]
Some of our processes around open sourcing have changed, notably everything has been switched github actions.

**Comment by repi** [comment]
@Jake-Shadle can you do a pass on this? @emilk recently ran into this with the new [puffin](https://github.com/embarkStudios/puffin) crate and has been stale for too long

**Comment by Jake-Shadle** [comment]
Yup!

**Comment by arirawr** [comment]
@Jake-Shadle has this been updated? If so let's move it to EmbarkStudios/opensource

**Comment by Jake-Shadle** [comment]
Nope, fell off my radar, I'll do it today.

**Comment by lpil** [comment]
I was going to do this as I had been working on the open source guides. Want me to take this @Jake-Shadle ?

**Comment by Jake-Shadle** [comment]
Go for it! :smile:

**Comment by lpil** [comment]
Thanks Jake!
