### ISSUE TITLE
docs.rs for private crate registry

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-ecosystem#47]
We've been using a private crate registry for over a year now (as discussed in #10, using cloudmith.io) and has been working  well. It is for some private code we have and for crates that are not fully ready yet to be open sourced on crates.io.

One thing we've been missing though is [docs.rs](https://docs.rs) generated documentation for our crates. We do use `cargo doc` and publish that but don't have documentation for different versions of crate and lack some of the docs.rs features and style.

Looks like there has been some very recent work on docs.rs towards this though which is great!

Tracking issues:
- [x] https://github.com/rust-lang/docs.rs/issues/767
- [ ] https://github.com/rust-lang/docs.rs/pull/813 (PR)

**Comment by l4l** [comment]
It seems the issue is resolved :tada:

**Comment by repi** [comment]
@l4l thanks for the heads up, that's nice!
