### ISSUE TITLE
Rename "master" branches to "main"

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-ecosystem#49]
For our internal and open source repositories.

We don't want where we develop to have a legacy name with these associations:

> mast•er măs′tər
>
>    n.
>    One that has control over another person, a group of persons, or a thing, especially.
>    n.
>    The owner or keeper of an animal.
>    n.
>    The owner of a slave.

and `main` is shorter!

Good blog post and guide: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

TODO:

- [x] [🌋 `ash-molten`](https://github.com/EmbarkStudios/ash-molten.git)
- [x] [👷 `buildkite-jobify`](https://github.com/EmbarkStudios/buildkite-jobify) - @Jake-Shadle 
- [x] [📜 `cargo-about`](https://github.com/EmbarkStudios/cargo-about) - @Jake-Shadle 
- [x] [❌ `cargo-deny`](https://github.com/EmbarkStudios/cargo-deny) - @Jake-Shadle 
- [x] [🎁 `cargo-fetcher`](https://github.com/EmbarkStudios/cargo-fetcher) - @Jake-Shadle 
- [x] [📦 `krates`](https://github.com/EmbarkStudios/krates) - @Jake-Shadle 
- [x] [🎳 `physx`](https://github.com/EmbarkStudios/physx-rs)
- [x] [🐏 `rpmalloc-rs`](https://github.com/EmbarkStudios/rpmalloc-rs)
- [x] [🆔 `spdx`](https://github.com/EmbarkStudios/spdx) - @Jake-Shadle 
- [x] [🔆 `superluminal-perf`](https://github.com/EmbarkStudios/superluminal-perf-rs)
- [x] [📂 `tame-gcs`](https://github.com/EmbarkStudios/tame-gcs) - @Jake-Shadle 
- [x] [🔐 `tame-oauth`](https://github.com/EmbarkStudios/tame-oauth) - @Jake-Shadle 
- [x] [🎨 `texture-synthesis`](https://github.com/EmbarkStudios/texture-synthesis)
- [x] `rust-ecosystem` (this repo)
- [x] [`opensource-template`](https://github.com/embarkStudios/opensource-template) cc @arirawr

**Comment by repi** [comment]
Heads up when renaming in the repos, there are references to `master` in our `.mergify.yml` and `CONTRIBUTING.md` that one has to do a commit to rename

**Comment by Jake-Shadle** [comment]
I think we're done!

**Comment by repi** [comment]
Awesome!

**Comment by arirawr** [comment]
That was quick! Great work! :D
