### ISSUE TITLE
`clippy::use_self` has too many false positives

### ISSUE THREAD

**Issue by davidpdrsn** [EmbarkStudios/rust-ecosystem#53]
`clippy::use_self` was previously part of our default set of clippy lints but we've had to remove it since it lead to false positives where applying its suggestions would fail to compile.

[This comment](https://github.com/rust-lang/rust-clippy/issues/4859#issuecomment-559566686) links to some of the issues.

One specific case we've run into is this

```rust
#![deny(clippy::use_self)]

pub struct Foo<T> {
    value: T,
}

impl<T> Foo<T> {
    pub fn new<K>(value: K) -> Foo<K> {
                            // ^^^^^^ changing this to `Self` wont work
        Foo { value }
    }
}
```

**Comment by repi** [comment]
Looks like https://github.com/rust-lang/rust-clippy/issues/4140 is the only remaining filed issue on the `use_self` lint, so once that has been resolved we may be able to add it back to a new version of our standard lints (#59) which would be nice!

**Comment by repi** [comment]
Looks like that clippy issue was fixed now, could you try to see if we have this issue still with latest nightly clippy @davidpdrsn ?

**Comment by davidpdrsn** [comment]
It seems to be working!

**Comment by repi** [comment]
Sweet! May be in Rust 1.54 or so then if it just got into nightly now, so could start using it then
