### ISSUE TITLE
iOS bitcode support

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-ecosystem#6]
Bitcode generation is required today for tvOS and watchOS, and may be required by iOS in the future? Could be faster also as one doesn't have to build for multiple targets.

This is still rather speculative and low priority at this time for us

- [ ] [Support Apple app store bitcode · Issue #35968 · rust-lang/rust](https://github.com/rust-lang/rust/issues/35968)

**Comment by repi** [comment]
This repo maintains Xcode-compatible bitcode support for iOS:
https://github.com/getditto/rust-bitcode

> In standard releases of Rust, the bitcode in ARM64 iOS targets is often incompatible with Xcode because they use different versions of LLVM. This is a known issue with no clear long-term solution yet.
> 
> This repository contains scripts for building and installing a custom Rust nightly toolchain where the Rust compiler's version of LLVM matches Xcode. Software built using this toolchain can be included in bitcode-enabled apps that will install on real iOS devices.
> 
> Binary releases of the toolchain will be created periodically and attached to this repository, at least until there is a better upstream solution.
> 
> This repository is maintained by Ditto. We use it ourselves and want to share it for the benefit of the Rust iOS community!

**Comment by adals** [comment]
when do you expect to run cargo build as like flutter run for bin apps?
because I have seen a lot of movement in Winit and amethyst crates to support ios

I am confused to learn flutter or rust for mobile development could you guide me plz?

**Comment by repi** [comment]
Closing this for now, iOS is not a target for us due to the heavy app store restrictions and incompatible TOS
