### ISSUE TITLE
Is it necessary to add a license for others to quote ？

### ISSUE THREAD

**Issue by ZhangHanDong** [EmbarkStudios/rust-ecosystem#70]
MIT or Apache ?

**Comment by repi** [comment]
You mean for this repository and the few markdown & toml files here? To identify which license they use?

**Comment by ZhangHanDong** [comment]
> You mean for this repository and the few markdown & toml files here? To identify which license they use?

yes. They can be referenced in some internal company coding specifications.

**Comment by repi** [comment]
Thanks for confirming, I'll add the standard "MIT OR Apache-2.0" licensing in a PR soon that we use for all of our open source repos

**Comment by ZhangHanDong** [comment]
thanks!
